# Generated by Django 4.2.7 on 2025-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Business Registration',
                'verbose_name_plural': 'Business Registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
