# Generated by Django 4.2.7 on 2025-10-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('multiplier', models.CharField(max_length=20)),
                ('current_price', models.CharField(max_length=50)),
                ('original_price', models.CharField(max_length=50)),
                ('badge', models.CharField(blank=True, help_text="Optional badge text (e.g., '50% off')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which plans are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['plan', 'display_order'],
            },
        ),
    ]
