# Generated by Django 4.2.7 on 2025-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutfeature_aboutpagesettings_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title for the screenshot', max_length=200)),
                ('image', models.ImageField(help_text='Upload screenshot image', upload_to='carousel/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which images are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
