# Generated by Django 4.2.7 on 2025-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.CharField(choices=[('🛡️', '🛡️ Shield (Security/Protection)'), ('⚡', '⚡ Lightning (Speed/Fast)'), ('📱', '📱 Mobile Phone (Mobile/App)'), ('🚀', '🚀 Rocket (Growth/Launch)'), ('💎', '💎 Gem (Premium/Quality)'), ('🔒', '🔒 Lock (Security)'), ('✨', '✨ Sparkles (Special/Features)'), ('🌟', '🌟 Star (Excellence)'), ('💡', '💡 Light Bulb (Ideas/Innovation)'), ('🎯', '🎯 Target (Focus/Goals)'), ('📊', '📊 Chart (Analytics/Data)'), ('🔔', '🔔 Bell (Notifications)'), ('💬', '💬 Chat (Communication)'), ('🤝', '🤝 Handshake (Partnership)'), ('🎨', '🎨 Artist Palette (Design/Creativity)'), ('🔍', '🔍 Magnifying Glass (Search)'), ('📈', '📈 Chart Up (Growth)'), ('💰', '💰 Money Bag (Finance/Pricing)'), ('🎁', '🎁 Gift (Rewards/Benefits)'), ('🏆', '🏆 Trophy (Achievement)'), ('🔥', '🔥 Fire (Hot/Popular)'), ('✅', '✅ Checkmark (Success/Done)'), ('🌐', '🌐 Globe (Global/Worldwide)'), ('👥', '👥 People (Community/Users)'), ('🔐', '🔐 Lock with Key (Privacy)'), ('⚙️', '⚙️ Gear (Settings/Configuration)'), ('📞', '📞 Phone (Contact)'), ('✉️', '✉️ Envelope (Email/Messages)'), ('📍', '📍 Pin (Location)'), ('🎉', '🎉 Party (Celebration)'), ('📝', '📝 Memo (Writing/Notes)'), ('💼', '💼 Briefcase (Business)'), ('🏠', '🏠 House (Home)'), ('🛒', '🛒 Shopping Cart (E-commerce)'), ('📦', '📦 Package (Delivery/Products)'), ('🎮', '🎮 Game Controller (Gaming)'), ('🎵', '🎵 Music Note (Music/Audio)'), ('📸', '📸 Camera (Photos/Media)'), ('🎬', '🎬 Movie Camera (Video)'), ('🏥', '🏥 Hospital (Health)'), ('🎓', '🎓 Graduation Cap (Education)'), ('🌍', '🌍 Earth (Environment)'), ('🚗', '🚗 Car (Transportation)'), ('✈️', '✈️ Airplane (Travel)'), ('🍕', '🍕 Pizza (Food)'), ('👨\u200d💼', '👨\u200d💼 Business Person (Business)'), ('👩\u200d💻', '👩\u200d💻 Developer (Tech)'), ('❤️', '❤️ Heart (Love/Care)'), ('👍', '👍 Thumbs Up (Approval)')], default='✨', help_text='Select an icon for this feature', max_length=50),
        ),
    ]
