# Generated by Django 4.2.7 on 2025-10-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_aboutfeature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Sell anything <span className="underline">safe</span> & fast on Oysloe.', help_text="Main headline for the landing page. Use <span className='underline'> for underlined text, <strong> for bold text, etc.")),
                ('subtitle', models.TextField(default='Improve your online presence and <strong>boost</strong> your business growth <strong className="text-10x">10x</strong>.', help_text="Sub-headline text. Use <strong> for bold text, <strong className='text-10x'> for special styling, etc.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
    ]
