# Generated by Django 4.2.7 on 2025-10-26 13:14

from django.db import migrations


def remove_underline_from_title(apps, schema_editor):
    """Remove underline span from existing landing page titles"""
    LandingPageSettings = apps.get_model('api', 'LandingPageSettings')
    for settings in LandingPageSettings.objects.all():
        if '<span class="underline">' in settings.title:
            settings.title = settings.title.replace('<span class="underline">', '').replace('</span>', '')
            settings.save()


def reverse_operation(apps, schema_editor):
    """Reverse operation - not needed but required for migrations"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_landingpagesettings'),
    ]

    operations = [
        migrations.RunPython(remove_underline_from_title, reverse_operation),
    ]
