# Generated by Django 4.2.7 on 2025-10-26 13:16

from django.db import migrations


def add_line_break_to_title(apps, schema_editor):
    """Add line break to existing landing page titles"""
    LandingPageSettings = apps.get_model('api', 'LandingPageSettings')
    for settings in LandingPageSettings.objects.all():
        # Replace "safe & fast" with "safe<br />& fast" if it doesn't already have the break
        if 'safe & fast' in settings.title and '<br />' not in settings.title:
            settings.title = settings.title.replace('safe & fast', 'safe<br />& fast')
            settings.save()
        # If title is exactly "Sell anything safe & fast on Oysloe." without line break
        elif settings.title == 'Sell anything safe & fast on Oysloe.':
            settings.title = 'Sell anything safe<br />& fast on Oysloe.'
            settings.save()


def reverse_operation(apps, schema_editor):
    """Reverse operation - not needed but required for migrations"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20251026_1314'),
    ]

    operations = [
        migrations.RunPython(add_line_break_to_title, reverse_operation),
    ]
