# Generated by Django 4.2.7 on 2025-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20251026_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesettings',
            name='subtitle',
            field=models.TextField(default='Improve your online presence and <strong>boost</strong> your business growth <strong class="text-10x">10x</strong>.', help_text="Sub-headline text. Use <strong> for bold text, <strong class='text-10x'> for special styling, etc."),
        ),
        migrations.AlterField(
            model_name='landingpagesettings',
            name='title',
            field=models.TextField(default='Sell anything safe<br />& fast on Oysloe.', help_text="Main headline for the landing page. Use <br /> for line breaks, <span class='underline'> for underlined text, <strong> for bold text, etc."),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=1, help_text='Number of pages viewed in this session')),
                ('is_bounce', models.BooleanField(default=False, help_text='True if user viewed only one page')),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id'], name='api_session_session_d594d3_idx'), models.Index(fields=['started_at'], name='api_session_started_f41189_idx'), models.Index(fields=['is_bounce'], name='api_session_is_boun_4bf75a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=255)),
                ('page_path', models.CharField(db_index=True, help_text="Page path (e.g., '/', '/about')", max_length=255)),
                ('referrer', models.CharField(blank=True, help_text='Referrer URL', max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page', models.IntegerField(default=0, help_text='Time spent on page in seconds')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='api_pagevie_session_7abb08_idx'), models.Index(fields=['page_path', 'timestamp'], name='api_pagevie_page_pa_5732f0_idx')],
            },
        ),
    ]
