# Generated by Django 4.2.7 on 2025-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_landingpagesettings_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_link', models.URLField(blank=True, help_text='WhatsApp group invite link (e.g., https://chat.whatsapp.com/...)', max_length=500)),
                ('button_text', models.CharField(default='Join WhatsApp Group', help_text='Text to display on the WhatsApp button', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide the WhatsApp button')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
    ]
